In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [22]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [23]:
## Define the vocabulary size
voc_size=10000

In [24]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1211, 4125, 489, 1816],
 [1211, 4125, 489, 7463],
 [1211, 7244, 489, 5121],
 [6760, 4868, 8576, 2025, 1990],
 [6760, 4868, 8576, 2025, 8802],
 [5075, 1211, 2634, 489, 7513],
 [9580, 7788, 3966, 2025]]

In [25]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [26]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1211 4125  489 1816]
 [   0    0    0    0 1211 4125  489 7463]
 [   0    0    0    0 1211 7244  489 5121]
 [   0    0    0 6760 4868 8576 2025 1990]
 [   0    0    0 6760 4868 8576 2025 8802]
 [   0    0    0 5075 1211 2634  489 7513]
 [   0    0    0    0 9580 7788 3966 2025]]


In [27]:
## feature representation
dim=10

In [28]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [33]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step


array([[[-0.02300295,  0.03131564, -0.02488146, -0.04638057,
          0.030782  , -0.01003074,  0.04014168, -0.01726419,
          0.03581006,  0.0219376 ],
        [-0.02300295,  0.03131564, -0.02488146, -0.04638057,
          0.030782  , -0.01003074,  0.04014168, -0.01726419,
          0.03581006,  0.0219376 ],
        [-0.02300295,  0.03131564, -0.02488146, -0.04638057,
          0.030782  , -0.01003074,  0.04014168, -0.01726419,
          0.03581006,  0.0219376 ],
        [-0.02300295,  0.03131564, -0.02488146, -0.04638057,
          0.030782  , -0.01003074,  0.04014168, -0.01726419,
          0.03581006,  0.0219376 ],
        [-0.03725182,  0.04938685, -0.02963727,  0.02068171,
          0.01873991, -0.0018534 ,  0.03865579, -0.01045422,
         -0.02234601, -0.00126154],
        [ 0.01543259, -0.0080465 ,  0.01878283,  0.02460878,
         -0.03576106,  0.02044214, -0.02488537, -0.01356532,
         -0.0129602 , -0.00270065],
        [ 0.03382057, -0.02299923,  0.00498333, -0.0

In [35]:
embedded_docs[0]

array([   0,    0,    0,    0, 1211, 4125,  489, 1816], dtype=int32)